#!/bin/sh
echo "*****                                                   ******"
echo "***** Cognizant Netcentric (https://www.netcentric.biz) ******"
echo "*****                                                   ******"
echo "*****              Running jest test  :)                ******"
echo "*****                                                   ******"

git stash -q --keep-index

npm test

status=$?

git stash pop -q

exit $status